Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -31,25 +31,29 @@ jobs:
           exit 1
         fi
 
+    - name: Check project structure
+      run: |
+          for student_dir in entregas/*; do
+            if [ -d "$student_dir" ]; then
+              # Check if expected directories/files are present in the student's submission
+              if [ ! -d "$student_dir/src/main/org/example/java" ]; then
+                echo "$student_dir is missing src/main/org/example/java directory!" >> structure-result.txt
+              fi
+              if [ ! -d "$student_dir/src/test/java" ]; then
+                echo "$student_dir is missing src/test/java directory!" >> structure-result.txt
+              fi
+            fi
+          done
+          if [ -f "structure-result.txt" ]; then
+            cat structure-result.txt
+            exit 1
+          fi
+
     - name: Set up JDK 20
       uses: actions/setup-java@v2
       with:
         java-version: '20'
         distribution: 'temurin'
-
-    - name: Check project structure
-      run: |
-        for student_dir in entregas/*; do
-          if [ -d "$student_dir" ]; then
-            # Check if expected directories/files are present in the student's submission
-            if [ ! -d "$student_dir/src/main/org/example/java" ]; then
-              echo "$student_dir is missing src/main/org/example/java directory!" >> structure-result.txt
-            fi
-            if [ ! -d "$student_dir/src/test/java" ]; then
-              echo "$student_dir is missing src/test/java directory!" >> structure-result.txt
-            fi
-          fi
-        done
 
     - name: Run Maven tests for all students
       run: |
@@ -57,7 +61,7 @@ jobs:
           if [ -d "$student_dir" ] && [ -f "$student_dir/pom.xml" ]; then
             echo "Running tests for $student_dir"
             cd "$student_dir"
-            mvn test -X || echo "Tests failed for $student_dir!" >> ../test-result.txt
+            mvn test || { echo "Tests failed for $student_dir!"; echo "Tests failed for $student_dir!" >> ../test-result.txt; exit 1; }
             cd ../..
           fi
         done
